from enum import StrEnum


class RiskSignalCode(StrEnum):
    HIGH_DEPOSIT = "HIGH_DEPOSIT"
    NIGHT_SESSION = "NIGHT_SESSION"
    FREQUENT_DEPOSIT = "FREQUENT_DEPOSIT"
    LIMIT_INCREASE = "LIMIT_INCREASE"
    FAILED_DEPOSIT = "FAILED_DEPOSIT"
    CANCELLED_WITHDRAWAL = "CANCELLED_WITHDRAWAL"
